name: Scrape Offers

on:
  schedule:
    - cron: '0 0 * * *' # Codziennie o północy
  workflow_dispatch: # Ręczne uruchomienie workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CHROME_BIN: ${{ secrets.CHROME_BIN }}
        run: |
          cd server
          node src/scraper.js
